#pragma once

#include "SFML\Graphics.hpp"
#include "SFML\Audio.hpp"
#include "SFML\Network.hpp"
#include "SFML\Window.hpp"

const sf::Color ATTACKARROWCOLOR(255, 0, 0, 128);
const sf::Color SUMMONARROWCOLOR(0, 255, 0, 128);

//const sf::Color DECKBORDERCOLOR(141, 211, 199);
//const sf::Color GRAVEYARDBORDERCOLOR(190, 186, 218);
//const sf::Color HANDBORDERCOLOR(128, 177, 211);
//const sf::Color MANABORDERCOLOR(179, 222, 105);
//const sf::Color SHIELDBORDERCOLOR(253, 180, 98);
//const sf::Color BATTLEBORDERCOLOR(251, 128, 114);
const sf::Color DECKBORDERCOLOR(141, 211, 199);
const sf::Color GRAVEYARDBORDERCOLOR(190, 186, 218);
const sf::Color HANDBORDERCOLOR(255, 255, 178);
const sf::Color MANABORDERCOLOR(254, 204, 92);
const sf::Color SHIELDBORDERCOLOR(253, 141, 60);
const sf::Color BATTLEBORDERCOLOR(227, 26, 28);

const float CARD_SCALE = 0.25;

const int CARDSEPERATION = 80;
const int CARDZONEOFFSET = 5;
const int CARDORIGINOFFSET = (307/2) * CARD_SCALE;

const int ZONEBORDERSIZE = 3;

const int CENTER = 390;
const int ZONEYOFFSET = CARDSEPERATION + 3 * CARDZONEOFFSET;
const int ZONE1X = 10;
const int ZONE2X = 700;

const int INFOBOXX = 800;
const int INFOBOXY = CENTER - ZONEYOFFSET * 3;

const int HOVERCARDX = INFOBOXX + CARDZONEOFFSET;
const int HOVERCARDY = INFOBOXY + CARDZONEOFFSET;

const int INFOTEXTX = INFOBOXX;
const int INFOTEXTY = CENTER + ZONEYOFFSET;

const int BUTTONLENGTH = 125;
const int BUTTONHEIGHT = 25;
const int BUTTONSEPERATION = 35;

const int CANCELBOXX = INFOTEXTX;
const int CANCELBOXY = INFOTEXTY + BUTTONSEPERATION;

const int ENDTURNX = CANCELBOXX;
const int ENDTURNY = CANCELBOXY + BUTTONSEPERATION;

const int QUITBUTTONX = ENDTURNX + 300;
const int QUITBUTTONY = ENDTURNY + 150;
const int QUITBUTTONLENGTH = BUTTONLENGTH;
const int QUITBUTTONHEIGHT = BUTTONHEIGHT;

const int CARDSEARCHX = HOVERCARDX + 250;
const int CARDSEARCHY = INFOBOXY;
const int CARDSEARCHSEPERATION = 20;
const int CARDSEARCHLENGTH = 150;
const int CARDSEARCHITEMCOUNT = 24;
